// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApxqk4GYjt4d3Pbo_7GFicNs4j7T3fBHI',
    appId: '1:470052620571:web:c6c30409f51093ca282bbe',
    messagingSenderId: '470052620571',
    projectId: 'demovps-d4779',
    authDomain: 'demovps-d4779.firebaseapp.com',
    storageBucket: 'demovps-d4779.firebasestorage.app',
    measurementId: 'G-7Y3C3Y2YLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtuxth63iTe6r2UAjPc7FBbpexlW3EdJw',
    appId: '1:470052620571:android:13bf66250cedbb5e282bbe',
    messagingSenderId: '470052620571',
    projectId: 'demovps-d4779',
    storageBucket: 'demovps-d4779.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTy8SwscMqSU0HIuq3VpVsZsCqW3kEHKo',
    appId: '1:470052620571:ios:1ee379f11eab38ea282bbe',
    messagingSenderId: '470052620571',
    projectId: 'demovps-d4779',
    storageBucket: 'demovps-d4779.firebasestorage.app',
    iosBundleId: 'com.example.demoVps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTy8SwscMqSU0HIuq3VpVsZsCqW3kEHKo',
    appId: '1:470052620571:ios:1ee379f11eab38ea282bbe',
    messagingSenderId: '470052620571',
    projectId: 'demovps-d4779',
    storageBucket: 'demovps-d4779.firebasestorage.app',
    iosBundleId: 'com.example.demoVps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApxqk4GYjt4d3Pbo_7GFicNs4j7T3fBHI',
    appId: '1:470052620571:web:87ecb18933befac5282bbe',
    messagingSenderId: '470052620571',
    projectId: 'demovps-d4779',
    authDomain: 'demovps-d4779.firebaseapp.com',
    storageBucket: 'demovps-d4779.firebasestorage.app',
    measurementId: 'G-0NB6XTT8RM',
  );
}
